version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.1
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elknet
    restart: always
  logstash:
    build:
      context: logstash/
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    networks:
      - elknet
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.1
    ports:
      - 5601:5601
    networks:
      - elknet
    restart: always

networks:
  elknet:
    driver: bridge
volumes:
  data:
    driver: local
